### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by ReneFroger** [gabebw/vim-rdio#1]
I admire you for creating this plugin. 

But as a minor detail... for the functions call in the command line, you need to chord-press `shift`-key every time. This is a flaw of VimScript. Actually, a flaw in my opion, because pressing shift every time before you enter a character, find I devious. 

You can get around this hassle, to build some behaviour into your awesome plugin. 

For example in your vimrc.

`autocmd VimEnter * call CmdAlias('rplay', 'RdioPlaylist')`

The rplay stands for RdioPlaylist. So when I type `:rplay`, I call RdioPlaylist. You need [CmdAlias](http://www.vim.org/scripts/script.php?script_id=746) for that, btw. 

Or if you want to work clean without any need for plugin: 

`cnoreabbrev <expr> rplay ((getcmdtype() is# ':'  && getcmdline() is# 'rplay')?('RdioPlaylist'):('rplay'))`

Not a big deal. But it will be ultimately when you enter all commands every day, time in, time out, all of your years, with the hassle of pressing `shift` simultaneously. 

Enjoy! :+1:

**Comment by gabebw** [comment]
Hi - thanks for the kind words!

I also find `:RdioNext` difficult to type, so I make keybindings that don't involve shift at all. My `<Leader>` key is comma, and I've bound `<Leader>rn` to `:RdioNext`. So all I have to do is `,rn` and I go to the next track! I don't even have to type a colon before the command. I have similar bindings for all of the other commands that you can see [in this file here](https://github.com/gabebw/dotfiles/blob/master/vim/rcplugins/rdio.vim).
